#Sprint 3, T02

##Nivell 1

In [45]:
import numpy as np
a = np.array([20,30,8,6,9,21,64,18], dtype = int)
print(a.ndim)
print(a.shape)

b = np.median(a)
c = np.mean(a)
print(b - c)

d = np.array([(20,30,8,6,9),(3,15,16,21,50),(30,15,16,68,50),(3,15,23,21,43),(3,15,16,21,56)], dtype = int)
print(d.ndim)
print(d.shape)
print(np.amax(d))

e = np.amax(d, axis=0)
print(e)
f = np.amax(d, axis=1)
print(f)

1
(8,)
-3.0
2
(5, 5)
68
[30 30 23 68 56]
[30 50 68 43 56]


##Nivell 2

###Broadcasting - Equal dimension

In [48]:
a = np.array([1.0, 2.0, 3.0], dtype = float)
b = np.array([2.0, 2.0, 2.0], dtype = float)
print(a * b)

[2. 4. 6.]


###Broadcasting - one of them is 1

In [53]:
a = np.array([(1.0, 2.0, 3.0),(4.0, 5.0, 6.0)], dtype = float)
b = np.array([1.0, 1.0, 1.0])
print(a * b)

[[1. 2. 3.]
 [4. 5. 6.]]
