#Sprint 3, T02

##Nivell 1

In [72]:
import numpy as np
a = np.array([20,30,8,6,9,21,64,18], dtype = int)
print("Firt array dimension is: ", (a.ndim))
print("Shape of this array is: ", (a.shape))

b = np.median(a)
c = np.mean(a)
print("Median - mean of this array is: ",(b - c))

d = np.array([(20,30,8,6,9),(3,15,16,21,50),(30,15,16,68,50),(3,15,23,21,43),(3,15,16,21,56)], dtype = int)
print("Maximum value of second array is: ", (np.amax(d)))

e = np.amax(d, axis=0)
print("Maximum values of axis 0 is: ", e)
f = np.amax(d, axis=1)
print("Maximum values of axis 1 is: ", f)

Firt array dimension is:  1
Shape of this array is:  (8,)
Median - mean of this array is:  -3.0
Maximum value of second array is:  68
Maximum values of axis 0 is:  [30 30 23 68 56]
Maximum values of axis 1 is:  [30 50 68 43 56]


##Nivell 2

###Broadcasting - Equal dimension - arrays must have same dimension

In [9]:
a = np.array([1.0, 2.0, 3.0], dtype = float)
b = np.array([2.0, 2.0, 2.0], dtype = float)
print(a * b)

[2. 4. 6.]


###Broadcasting - One of them is 1 - arrays of different dimensions

In [10]:
a = np.array([(1.0, 2.0, 3.0),(4.0, 5.0, 6.0)], dtype = float)
b = np.array([1.0, 1.0, 1.0])
print(a * b)

[[1. 2. 3.]
 [4. 5. 6.]]


###Indexation

In [73]:
a = np.array([(1.0, 2.0, 3.0),(4.0, 5.0, 8.0),(7.0, 8.0, 12.0)], dtype = float)
print("Sum of numbers in column3 + row3: ", a[0, 2] + a[1, 2] + a[2, 2] + a[2, 0] + a[2, 1] + a[2, 2])

Sum of numbers in column3 + row3:  50.0


###Divisible by 4?

In [74]:
a = np.array([(1.0, 2.0, 3.0),(4.0, 5.0, 8.0),(7.0, 8.0, 12.0)], dtype = float)
filter_arr = []
for element in a:

  if np.any(element % 4 == 0,axis = 0):
    filter_arr.append(True)
  else:
    filter_arr.append(False)
    
print(filter_arr)

[False, True, True]


###Reshaping, flattering with mask

In [75]:
a = np.array([(1.0, 2.0, 3.0),(4.0, 5.0, 8.0),(7.0, 8.0, 12.0)], dtype = float)
filter_arr = []
for element in a:

  if np.any(element % 4 == 0,axis = 0):
    filter_arr.append(True)
  else:
    filter_arr.append(False)
    
b = a[filter_arr]
newarr = b.reshape(-1)
print(newarr)

[ 4.  5.  8.  7.  8. 12.]
